# Generated by Django 4.1.3 on 2022-12-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_time_unity',
            new_name='preparation_time_unit',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_unity',
            new_name='servings_unit',
        ),
    ]
